export class UpdateFichaDto {
  // Dados Pessoais
  nome_completo?: string;
  nome_mae?: string;
  telefone?: string;
  email?: string;
  cpf?: string;
  rg?: string;
  orgao_emissor?: string;
  data_nascimento?: string;
  estado_civil?: string;
  nacionalidade?: string;
  profissao?: string;
  // Endereço
  cep?: string;
  logradouro?: string;
  numero?: string;
  bairro?: string;
  cidade?: string;
  estado_uf?: string;
  // Contrato
  nome_empregador?: string;
  cnpjcpf_empregador?: string;
  data_admissao?: string;
  data_saida?: string;
  situacao_atual?: string;
  motivo_saida?: string;
  ctps_numero?: string;
  pis_pasep?: string;
  ctps_assinada_corretamente?: string;
  periodo_sem_carteira?: string;
  funcao?: string;
  salario?: string;
  periodicidade_pagamento?: string;
  atividades_realizadas?: string;
  // Jornada
  horario_entrada?: string;
  horario_saida?: string;
  tempo_intervalo?: string;
  dias_trabalhados?: string;
  fazia_horas_extras?: string;
  qtd_horas_extras_dia?: string;
  tipo_controle_ponto?: string;
  horas_extras_pagas_corretamente?: string;
  possui_copia_ponto?: string;
  ponto_refletia_realidade?: string;
  horario_real_trabalhado?: string;
  // Pagamentos
  recebia_por_fora?: string;
  outro_valor_por_fora?: string;
  recebia_vale_transporte?: string;
  precisava_vt?: string;
  valor_gasto_vt?: string;
  premio_comissao?: string;
  natureza_premio?: string;
  valor_premio?: string;
  periodicidade_premio?: string;
  tem_prova_premio?: string;
  periodicidade_comissao?: string;
  natureza_comissao?: string;
  valor_comissao?: string;
  tem_prova_comissao?: string;
  // Segurança
  ambiente_insalubre_perigoso?: string;
  ambiente_insalubre?: string;
  forneciam_epis?: string;
  sofreu_acidente?: string;
  detalhes_acidente?: string;
  recebeu_auxilio_b91?: string;
  tempo_cessacao_beneficio?: string;
  sofreu_assedio_moral?: string;
  detalhes_assedio_moral?: string;
  // FGTS
  fgts_depositado?: string;
  fgts_sacado?: string;
  // Verbas
  tem_ferias_pendentes?: string;
  tem_decimo_terceiro_pendente?: string;
  detalhes_verbas_pendentes?: string;
  // Testemunhas
  possui_testemunhas?: string;
  detalhes_testemunhas?: string;
  possui_provas_documentais?: string;
  detalhes_provas_documentais?: string;
  // Resumo
  motivos_reclamacao?: string;
}
